services:
  - type: web
    name: ncp-wheels
    env: python
    region: oregon
    buildCommand: ./build.sh
    startCommand: gunicorn config.wsgi:application --bind 0.0.0.0:10000 --keyfile=key.pem --certfile=cert.pem
    envVars:
      - key: DJANGO_SETTINGS_MODULE
        value: config.settings_prod
      - key: PYTHON_VERSION
        value: 3.9.18
      - key: WEB_CONCURRENCY
        value: 4
      - key: DB_HOST
        value: srv1757.hstgr.io
      - key: DB_PORT
        value: 3306
      - key: DB_NAME
        value: u466615417_ncpwheels
      - key: DB_USER
        value: u466615417_sameergul321
      - key: DB_PASSWORD
        sync: false
      - key: EMAIL_HOST
        value: smtp.hostinger.com
      - key: EMAIL_PORT
        value: 587
      - key: EMAIL_HOST_USER
        sync: false
      - key: EMAIL_HOST_PASSWORD
        sync: false
      - key: DEFAULT_FROM_EMAIL
        sync: false
      - key: PORT
        value: 10000
      - key: SECURE_SSL_REDIRECT
        value: "true"
      - key: SECURE_PROXY_SSL_HEADER_NAME
        value: "HTTP_X_FORWARDED_PROTO"
      - key: SECURE_PROXY_SSL_HEADER_VALUE
        value: "https"
      - key: SECURE_MIN_TLS_VERSION
        value: "TLS1.0"
    autoDeploy: true
    plan: free
    runtime: python3.9
    buildFilter:
      paths:
      - '**/*.py'
      - '**/*.html'
      - requirements.txt
      - build.sh
    preInstallCommand: |
      apt-get update && apt-get install -y default-libmysqlclient-dev build-essential pkg-config python3-dev
