# Generated by Django 5.1.5 on 2025-01-30 13:00

import django.core.validators
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=255, null=True)),
                ('slug', models.SlugField(blank=True, max_length=255, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('price', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('condition', models.CharField(choices=[('new', 'New'), ('used', 'Used')], default='used', max_length=10)),
                ('year', models.PositiveIntegerField(default=2000, validators=[django.core.validators.MinValueValidator(1900), django.core.validators.MaxValueValidator(2100)])),
                ('mileage', models.PositiveIntegerField(blank=True, help_text='Mileage in kilometers', null=True)),
                ('brand', models.CharField(choices=[('toyota', 'Toyota'), ('honda', 'Honda'), ('suzuki', 'Suzuki'), ('nissan', 'Nissan'), ('hyundai', 'Hyundai'), ('kia', 'Kia'), ('mercedes', 'Mercedes'), ('bmw', 'BMW'), ('audi', 'Audi'), ('volkswagen', 'Volkswagen'), ('other', 'Other')], default='other', max_length=50, verbose_name='Brand')),
                ('model', models.CharField(default='Unknown', max_length=100)),
                ('transmission', models.CharField(choices=[('automatic', 'Automatic'), ('manual', 'Manual'), ('cvt', 'CVT')], default='manual', max_length=20)),
                ('fuel_type', models.CharField(choices=[('petrol', 'Petrol'), ('diesel', 'Diesel'), ('hybrid', 'Hybrid'), ('electric', 'Electric'), ('cng', 'CNG')], default='petrol', max_length=20)),
                ('engine_size', models.DecimalField(blank=True, decimal_places=1, help_text='Engine size in liters', max_digits=4, null=True)),
                ('power', models.PositiveIntegerField(blank=True, help_text='Engine power in horsepower', null=True)),
                ('body_type', models.CharField(choices=[('sedan', 'Sedan'), ('hatchback', 'Hatchback'), ('suv', 'SUV'), ('crossover', 'Crossover'), ('coupe', 'Coupe'), ('convertible', 'Convertible'), ('wagon', 'Wagon'), ('van', 'Van'), ('truck', 'Truck')], default='sedan', max_length=20)),
                ('color', models.CharField(choices=[('black', 'Black'), ('white', 'White'), ('silver', 'Silver'), ('gray', 'Gray'), ('red', 'Red'), ('blue', 'Blue'), ('brown', 'Brown'), ('green', 'Green'), ('other', 'Other')], default='white', max_length=20)),
                ('doors', models.PositiveSmallIntegerField(default=4, validators=[django.core.validators.MinValueValidator(2), django.core.validators.MaxValueValidator(6)])),
                ('seats', models.PositiveSmallIntegerField(default=5, validators=[django.core.validators.MinValueValidator(2), django.core.validators.MaxValueValidator(10)])),
                ('city', models.CharField(blank=True, max_length=100, null=True)),
                ('province', models.CharField(blank=True, choices=[('punjab', 'Punjab'), ('sindh', 'Sindh'), ('kpk', 'Khyber Pakhtunkhwa'), ('balochistan', 'Balochistan'), ('gilgit', 'Gilgit-Baltistan'), ('ajk', 'Azad Kashmir'), ('islamabad', 'Islamabad Capital Territory')], max_length=100, null=True)),
                ('location_details', models.TextField(blank=True)),
                ('featured', models.BooleanField(default=False)),
                ('featured_until', models.DateTimeField(blank=True, null=True)),
                ('views', models.PositiveIntegerField(default=0)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('published', 'Published'), ('sold', 'Sold'), ('archived', 'Archived')], default='draft', max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('sold_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CarFeature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('category', models.CharField(choices=[('safety', 'Safety'), ('comfort', 'Comfort'), ('entertainment', 'Entertainment'), ('performance', 'Performance'), ('exterior', 'Exterior'), ('interior', 'Interior'), ('other', 'Other')], max_length=20)),
                ('description', models.TextField(blank=True)),
            ],
            options={
                'ordering': ['category', 'name'],
            },
        ),
        migrations.CreateModel(
            name='CarImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='car_images/')),
                ('is_primary', models.BooleanField(default=False)),
                ('order', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='FeaturedListing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('end_date', models.DateTimeField()),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PriceHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.DecimalField(decimal_places=2, max_digits=12)),
                ('date', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'Price histories',
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='SearchHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('query', models.JSONField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'Search histories',
                'ordering': ['-created_at'],
            },
        ),
    ]
