# Generated by Django 5.1.5 on 2025-01-30 13:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cars', '0001_initial'),
        ('payments', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='seller',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='car_listings', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='car',
            name='features',
            field=models.ManyToManyField(blank=True, to='cars.carfeature'),
        ),
        migrations.AddField(
            model_name='carimage',
            name='car',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='cars.car'),
        ),
        migrations.AddField(
            model_name='featuredlisting',
            name='car',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='featured_listing', to='cars.car'),
        ),
        migrations.AddField(
            model_name='featuredlisting',
            name='transaction',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='featured_listing', to='payments.transaction'),
        ),
        migrations.AddField(
            model_name='pricehistory',
            name='car',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='price_history', to='cars.car'),
        ),
        migrations.AddField(
            model_name='searchhistory',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='car_searches', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='car',
            index=models.Index(fields=['brand', 'model', 'year'], name='cars_car_brand_c15220_idx'),
        ),
        migrations.AddIndex(
            model_name='car',
            index=models.Index(fields=['price'], name='cars_car_price_f6b08b_idx'),
        ),
        migrations.AddIndex(
            model_name='car',
            index=models.Index(fields=['city', 'province'], name='cars_car_city_3568a5_idx'),
        ),
        migrations.AddIndex(
            model_name='car',
            index=models.Index(fields=['created_at'], name='cars_car_created_f3c7e2_idx'),
        ),
        migrations.AddIndex(
            model_name='car',
            index=models.Index(fields=['featured'], name='cars_car_feature_9c207c_idx'),
        ),
        migrations.AddIndex(
            model_name='featuredlisting',
            index=models.Index(fields=['is_active', '-start_date'], name='cars_featur_is_acti_ad1bba_idx'),
        ),
        migrations.AddIndex(
            model_name='featuredlisting',
            index=models.Index(fields=['end_date'], name='cars_featur_end_dat_a4bb7b_idx'),
        ),
    ]
