# Generated by Django 5.1.5 on 2025-02-01 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymentgatewayconfig',
            name='gateway',
            field=models.CharField(choices=[('easypaisa', 'EasyPaisa'), ('bankalfalah', 'Bank Alfalah')], max_length=20, unique=True),
        ),
    ]
