# Generated by Django 5.1.5 on 2025-01-30 13:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('analytics', '0001_initial'),
        ('cars', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='dailyanalytics',
            name='featured_listing',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily_analytics', to='cars.featuredlisting'),
        ),
        migrations.AddField(
            model_name='featuredlistinganalytics',
            name='featured_listing',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='analytics', to='cars.featuredlisting'),
        ),
        migrations.AddField(
            model_name='featuredlistinginteraction',
            name='featured_listing',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interactions', to='cars.featuredlisting'),
        ),
    ]
